web:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /var/www/docker/nginx:/etc/nginx/conf.d
    - /var/www/:/var/www
  links:
    - php7:php

php7:
  restart: always
  image: php:7.0.2-fpm
  volumes:
    - /var/www:/var/www
  links:
    - db:db

# php5:
#   restart: always
#   image: php:5.6.17-fpm
#   volumes:
#     - /var/www:/var/www
#   links:
#     - db:db

db:
  restart: always
  image: mysql
  volumes:
    - /var/lib/boot2docker/mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root

adminer:
  restart: always
  image: clue/adminer
  ports:
    - "8080:80"
  links:
    - db:db
